# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# CI Pipeline YAML configuration
# This pipeline builds the web application, runs tests, and generates a Docker image.

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    containerRegistry: 'azure-container-connection' # Specify your container registry service connection name
    command: 'build'
    Dockerfile: '**/Dockerfile' # Path to your Dockerfile

- task: Docker@2
  displayName: 'Push Docker Image to Registry'
  inputs:
    containerRegistry: 'azure-container-connection' # Specify your container registry service connection name
    command: 'push'
    Dockerfile: '**/Dockerfile' # Path to your Dockerfile

# Add more steps here for building the web application and running tests

# azure-container-connection
# Azure Container Registry Application