# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - main

# pool:
#   vmImage: ubuntu-latest

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

trigger:
- main  # trigger the pipeline on main update.

pool:
  vmImage: 'ubuntu-latest' 

steps:
- task: PowerShell@2
  displayName: 'Get Latest Tag'
  inputs:
    targetType: 'inline'
    script: |
      $tags = Invoke-RestMethod -Uri "https://registry.hub.docker.com/v2/repositories/mohammadfleity2002/project1-arabiflower/tags/" | Select-Object -ExpandProperty results | Select-Object -ExpandProperty name
      $latestTag = $tags | Sort-Object -Property { [version] $_ } | Select-Object -Last 1
      Write-Host "Latest Tag: $latestTag"
      echo "##vso[task.setvariable variable=LatestTag]$latestTag"

- task: Docker@2
  displayName: 'Login to Docker Hub'
  inputs:
    command: login
    containerRegistry: 'ArabiFlower-Docker'  # Docker Hub service connection
    username: $(mohammadfleity2002)
    password: $(MohammadDockerPassword2002)

- script: |
    docker pull mohammadfleity2002/project1-arabiflower:$(latestTag)
    docker run -d -p 8080:80 mohammadfleity2002/project1-arabiflower:$(latestTag)
  displayName: 'Deploy to Docker'
